# Generated by Django 2.0.3 on 2018-04-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_uuid', models.CharField(max_length=64)),
                ('image_dir', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_uuid', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255, null=True)),
                ('body', models.CharField(max_length=65535, null=True)),
                ('read_time', models.CharField(max_length=4, null=True)),
                ('approved', models.IntegerField(default=0, max_length=2)),
                ('created_date', models.DateTimeField()),
                ('modified_timestamp', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete='CASCADE', related_name='created_by', to='user.User')),
                ('header_image_id', models.ForeignKey(on_delete='CASCADE', to='post.Image')),
                ('last_modified_by', models.ForeignKey(on_delete='CASCADE', related_name='last_modified_by', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='PostStatus',
            fields=[
                ('post_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_status', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='post_status_id',
            field=models.ForeignKey(on_delete='CASCADE', to='post.PostStatus'),
        ),
        migrations.AddField(
            model_name='post',
            name='section_id',
            field=models.ForeignKey(on_delete='CASCADE', to='post.Section'),
        ),
    ]
