# Generated by Django 2.0.3 on 2018-04-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='approved',
            field=models.IntegerField(default=0),
        ),
    ]
