# Generated by Django 2.0.3 on 2018-04-04 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20180404_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='modified_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
