# Generated by Django 2.0.4 on 2018-05-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20180517_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_uuid',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
