# Generated by Django 2.0.3 on 2018-04-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('action_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorWebPage',
            fields=[
                ('visitor_web_page_id', models.AutoField(primary_key=True, serialize=False)),
                ('visited_page_url', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='WebPageAction',
            fields=[
                ('web_page_action_id', models.AutoField(primary_key=True, serialize=False)),
                ('web_page_action_uuid', models.CharField(max_length=64)),
                ('created_date', models.DateTimeField()),
                ('action_id', models.ForeignKey(on_delete='CASCADE', to='action.Action')),
                ('web_page_id', models.ForeignKey(on_delete='CASCADE', to='action.VisitorWebPage')),
            ],
        ),
    ]
