# Generated by Django 2.0.3 on 2018-04-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('action', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorwebpage',
            name='visited_post_id',
            field=models.ForeignKey(on_delete='CASCADE', to='post.Post'),
        ),
        migrations.AddField(
            model_name='visitorwebpage',
            name='visitor_id',
            field=models.ForeignKey(on_delete='CASCADE', to='user.Visitor'),
        ),
    ]
