# Generated by Django 2.0.3 on 2018-04-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('capability_id', models.AutoField(primary_key=True, serialize=False)),
                ('capability', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RoleCapability',
            fields=[
                ('role_capability_id', models.AutoField(primary_key=True, serialize=False)),
                ('capability_id', models.ForeignKey(on_delete='CASCADE', to='user.Capability')),
                ('role_id', models.ForeignKey(on_delete='CASCADE', to='user.Role')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_uuid', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_role_uuid', models.CharField(max_length=64)),
                ('role_id', models.ForeignKey(on_delete='CASCADE', to='user.Role')),
                ('user_id', models.ForeignKey(on_delete='CASCADE', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserToVisitor',
            fields=[
                ('user_to_visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField()),
                ('user_id', models.ForeignKey(on_delete='CASCADE', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_uuid', models.CharField(max_length=64)),
                ('session_id', models.CharField(max_length=64)),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='usertovisitor',
            name='visitor_id',
            field=models.ForeignKey(on_delete='CASCADE', to='user.Visitor'),
        ),
    ]
