# Generated by Django 2.0.4 on 2018-05-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180513_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_uuid',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
