# Generated by Django 2.0.4 on 2018-05-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180513_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertovisitor',
            name='visitor_id',
            field=models.ForeignKey(on_delete='CASCADE', to='user.Visitor', unique=True),
        ),
    ]
