# Generated by Django 2.0.4 on 2018-05-18 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_visitor_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertovisitor',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='usertovisitor',
            name='visitor_id',
        ),
        migrations.DeleteModel(
            name='UserToVisitor',
        ),
    ]
