# Generated by Django 2.0.4 on 2018-05-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180517_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete='SET_DEFAULT', to='user.User'),
        ),
    ]
