# Generated by Django 2.0.4 on 2018-05-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20180517_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete='SET_DEFAULT', to='user.User'),
        ),
    ]
