# Generated by Django 2.0.4 on 2018-05-19 03:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_auto_20180517_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_user_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete='SET_DEFAULT', to=settings.AUTH_USER_MODEL),
        ),
    ]
