# Generated by Django 2.0.4 on 2018-05-20 03:11

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0010_user_auth_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdminSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_admin_session_uuid', models.CharField(max_length=64, unique=True)),
                ('session_token', models.CharField(max_length=64)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_DEFAULT', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user_role_uuid',
            field=models.CharField(default=uuid.UUID('c983ae22-dfff-43b2-8bc9-cdf59b992436'), max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_uuid',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='useradminsession',
            name='user_id',
            field=models.ForeignKey(on_delete='SET_DEFAULT', to=settings.AUTH_USER_MODEL),
        ),
    ]
