# Generated by Django 2.0.4 on 2018-05-20 03:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20180520_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='user_role_uuid',
            field=models.CharField(default=uuid.UUID('379b61e9-9f70-40c0-8dd2-16a358b658b9'), max_length=64, unique=True),
        ),
    ]
