# Generated by Django 2.0.4 on 2018-05-20 04:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20180520_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='user_role_uuid',
            field=models.CharField(default=uuid.UUID('4cd314af-09ea-4d80-bfb7-dfefc2fc8412'), max_length=64, unique=True),
        ),
    ]
