# Generated by Django 2.0.4 on 2018-05-20 04:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20180520_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradminsession',
            name='user_id',
            field=models.ForeignKey(on_delete='SET_DEFAULT', to='user.User'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user_role_uuid',
            field=models.CharField(default=uuid.UUID('91a74e6e-3433-40f5-a05f-b2b29714d3fa'), max_length=64, unique=True),
        ),
    ]
