# Generated by Django 2.0.4 on 2018-05-31 04:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20180520_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user_role_uuid',
            field=models.CharField(default=uuid.UUID('e1fd0c46-910e-492e-bdc9-94d35605e5e0'), max_length=64, unique=True),
        ),
    ]
